from pathlib import Path
from typing import List, Optional

from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse
from fastapi.templating import Jinja2Templates

from .data import repository

app = FastAPI(
    title='Engagement Gauge API',
    description='Serve engagement statistics generated by engagement_gauge_dev.py',
    version='0.1.0',
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=['*'],
    allow_methods=['*'],
    allow_headers=['*'],
)


templates = Jinja2Templates(directory=str(Path(__file__).resolve().parent / 'templates'))


@app.get('/', summary='Engagement Gauge home', response_class=HTMLResponse)
def home_view(request: Request) -> HTMLResponse:
    return templates.TemplateResponse(
        'index.html',
        {'request': request, 'last_loaded': repository.last_updated()},
    )


@app.get('/health', summary='Health check')
def health() -> dict:
    return {'status': 'ok', 'last_loaded': repository.last_updated()}


@app.get('/devices', summary='List devices with engagement summaries')
def list_devices() -> dict:
    summaries = repository.device_summaries()
    return {
        'devices': summaries,
        'count': len(summaries),
        'last_loaded': repository.last_updated(),
        'data_source': str(repository.db_path),
    }


@app.get('/devices/{device_id}', summary='Detailed metrics for a specific device')
def device_details(device_id: str) -> dict:
    drives = repository.drives_for_device(device_id)
    if not drives:
        raise HTTPException(status_code=404, detail=f'Device {device_id} not found')

    summary = repository.device_summary(device_id)
    return {
        'device': summary,
        'drives': repository.format_drive_details(drives),
        'last_loaded': repository.last_updated(),
    }


@app.get('/stats', summary='CLI-style engagement summary', response_class=HTMLResponse)
def stats_view(request: Request) -> HTMLResponse:
    summary_text = repository.cli_summary(include_device_columns=False)
    return templates.TemplateResponse('stats.html', {'request': request, 'summary': summary_text})


@app.get('/stats_mod', summary='Modern engagement dashboard', response_class=HTMLResponse)
def stats_mod_view(request: Request) -> HTMLResponse:
    summaries = repository.device_summaries()
    devices = []
    for summary in summaries:
        device_id = summary.get('device_id')
        drives = repository.format_drive_details(repository.drives_for_device(device_id))
        devices.append({
            'summary': summary,
            'drives': drives,
        })

    context = {
        'request': request,
        'devices': devices,
        'last_loaded': repository.last_updated(),
    }
    return templates.TemplateResponse('stats_mod.html', context)


@app.get('/compare', summary='Compare engagement stats by device, branch, and speed bucket', response_class=HTMLResponse)
def compare_view(
    request: Request,
    device: Optional[List[str]] = Query(None),
    branch: Optional[List[str]] = Query(None),
    speed_bucket: str = 'all',
) -> HTMLResponse:
    comparison = repository.comparison_summary(
        device_ids=device,
        branch=branch,
        speed_bucket=speed_bucket,
    )
    context = {
        'request': request,
        'comparison': comparison,
        'last_loaded': repository.last_updated(),
    }
    return templates.TemplateResponse('compare.html', context)


@app.get('/api/compare', summary='Comparison stats by device, branch, and speed bucket')
def api_compare_view(
    device: Optional[List[str]] = Query(None),
    branch: Optional[List[str]] = Query(None),
    speed_bucket: str = 'all',
) -> dict:
    return repository.comparison_summary(
        device_ids=device,
        branch=branch,
        speed_bucket=speed_bucket,
    )
@app.get('/total_stats', summary='Modern engagement dashboard with totals', response_class=HTMLResponse)
def total_stats_view(request: Request) -> HTMLResponse:
    summary = repository.grand_total_summary()
    context = {
        'request': request,
        'summary': summary,
        'last_loaded': repository.last_updated(),
    }
    return templates.TemplateResponse('total_stats.html', context)


@app.get('/api/total_stats', summary='Grand total summary statistics')
def api_total_stats_view() -> dict:
    summary = repository.grand_total_summary()
    return summary


@app.get('/total_stats/style1', summary='Total stats - Style 1', response_class=HTMLResponse)
def total_stats_style1_view(request: Request) -> HTMLResponse:
    summary = repository.grand_total_summary()
    context = {
        'request': request,
        'summary': summary,
        'last_loaded': repository.last_updated(),
    }
    return templates.TemplateResponse('total_stats_style1.html', context)


@app.get('/total_stats/style2', summary='Total stats - Style 2', response_class=HTMLResponse)
def total_stats_style2_view(request: Request) -> HTMLResponse:
    summary = repository.grand_total_summary()
    context = {
        'request': request,
        'summary': summary,
        'last_loaded': repository.last_updated(),
    }
    return templates.TemplateResponse('total_stats_style2.html', context)


@app.get('/total_stats/style3', summary='Total stats - Style 3', response_class=HTMLResponse)
def total_stats_style3_view(request: Request) -> HTMLResponse:
    summary = repository.grand_total_summary()
    context = {
        'request': request,
        'summary': summary,
        'last_loaded': repository.last_updated(),
    }
    return templates.TemplateResponse('total_stats_style3.html', context)
@app.get('/total_stats/style4', summary='Total stats - Style 4', response_class=HTMLResponse)
def total_stats_style4_view(request: Request) -> HTMLResponse:
    summary = repository.grand_total_summary()
    context = {
        'request': request,
        'summary': summary,
        'last_loaded': repository.last_updated(),
    }
    return templates.TemplateResponse('total_stats_style4.html', context)
